name: Rust

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check the formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Install package handler
      if: startsWith(github.event.ref, 'refs/tags/')
      run: cargo install cargo-deb

    - name: Set Cargo.toml version
      if: startsWith(github.event.ref, 'refs/tags/')
      shell: bash
      env:
        RELEASE_TAG: ${GITHUB_REF#refs/*/}
      run: |
        mv Cargo.toml Cargo.toml.orig
        sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml.orig >Cargo.toml
        mv Cargo.lock Cargo.lock.orig
        sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.lock.orig >Cargo.lock

    - name: Create package
      if: startsWith(github.event.ref, 'refs/tags/')
      run: cargo deb

    - name: Publish the release
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{github.workspace}}/target/debian/*.deb