name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check the formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Install package handler
      if: startsWith(github.event.ref, 'refs/tags/')
      run: rustup update && cargo install cargo-deb

    - name: Create package
      if: startsWith(github.event.ref, 'refs/tags/')
      run: cargo deb

    - name: Publish the release
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{github.workspace}}/target/debian/*.deb